 common_sysctl_list:
  - { name: 'net.ipv4.tcp_tw_recycle', value: "0" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.ipv4.tcp_tw_reuse', value: "1" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.ipv4.tcp_max_tw_buckets', value: "2000" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.ipv4.tcp_max_syn_backlog', value: "65536" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.ipv4.tcp_keepalive_time', value: "60" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.core.netdev_max_backlog', value: "262144" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.ipv4.tcp_synack_retries', value: "3" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.ipv4.tcp_syn_retries', value: "3" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.ipv4.tcp_fin_timeout', value: "5" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.ipv4.tcp_orphan_retries', value: "3" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.core.rmem_max', value: "16503552" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.core.wmem_max', value: "16503552" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.ipv4.tcp_rmem', value: "4096 87380 16503552" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.ipv4.tcp_wmem', value: "4096 65536 16503552" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.core.somaxconn', value: "65536" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'vm.swappiness', value: "0" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'fs.file-max ', value: "655360" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.ipv4.ip_local_port_range ', value: "1024 65000" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.nf_conntrack_max', value: "2097152" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.netfilter.nf_conntrack_tcp_timeout_established ', value: "14400" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.bridge.bridge-nf-call-ip6tables', value: "1" , state: "present", sysctl_file: "/etc/sysctl.conf" }
  - { name: 'net.bridge.bridge-nf-call-iptables', value: "1" , state: "present", sysctl_file: "/etc/sysctl.conf" }