---
# defaults file for k8s init role.

# for ntp server
ntp_server_address: 172.24.0.29

# for docker configuration.
bip_address: 172.23.0.1/20
registry_mirrors_url: https://registry.docker-cn.com

# for install k8s package version.
docker_ce_version: 17.03.3.ce-1.el7
k8s_package_version: 1.11.6-0