---
# defaults file for k8s init role.

# for ntp server
ntp_server_address: xxxx

# for docker configuration.
bip_address: xxxx
registry_mirrors_url: https://registry.docker-cn.com

# for install k8s package version.
docker_ce_version: 17.03.3~ce-0~ubuntu-xenial
k8s_package_version: 1.11.6-00
